return {
	"folke/which-key.nvim",
	dependencies = { "echasnovski/mini.icons" },
	event = "VeryLazy",
	opts = {
		icons = {
			mappings = false,
		},
		spec = {
			mode = { "n", "v" },
			{ "<leader>b", group = "buffer" },
			{ "<leader>c", group = "code" },
			{ "<leader>cp", group = "package" },
			{ "<leader>f", group = "find" },
			{ "<leader>g", group = "git" },
			{ "<leader>gh", group = "github" },
			{ "<leader>ghy", group = "yank" },
			{ "<leader>h", group = "hunk" },
			{ "<leader>ht", group = "toggle" },
			{ "<leader>q", group = "quit/session" },
			{ "<leader>r", group = "replace" },
			{ "<leader>s", group = "search" },
			{ "<leader>t", group = "test" },
			{ "<leader>w", group = "windows" },
			{ "<leader>x", group = "diagnostics/quickfix" },
			{ "[", group = "prev" },
			{ "]", group = "next" },
			{ "g", group = "goto" },
		},
	},
}
